/* ═══════════════════════════════════════════════
   PATHOGEN - Game Data
   Countries, Disease Types, Evolution Tree
   ═══════════════════════════════════════════════ */

// ─── COUNTRY DATA ───────────────────────────────
// iso: numeric ISO 3166-1 (matches topojson world-atlas)
// climate: temperate | tropical | arid | cold
// wealth: rich | middle | poor
// airports: 0-5 (air connectivity)
// ports: 0-3 (sea connectivity)
// borders: [iso codes of land neighbors]
// healthcare: 0-1 (affects cure speed contribution and death rate)

const COUNTRIES_DATA = [
  // ─── NORTH AMERICA
  { iso: 840, name: 'USA',            pop: 335000000, climate: 'temperate', wealth: 'rich',   airports: 5, ports: 3, borders: [124, 484], healthcare: 0.95 },
  { iso: 124, name: 'Canada',         pop: 38000000,  climate: 'cold',      wealth: 'rich',   airports: 4, ports: 2, borders: [840],       healthcare: 0.92 },
  { iso: 484, name: 'Mexico',         pop: 130000000, climate: 'tropical',  wealth: 'middle', airports: 3, ports: 2, borders: [840, 320],   healthcare: 0.65 },

  // ─── CENTRAL AMERICA & CARIBBEAN
  { iso: 320, name: 'Guatemala',      pop: 18000000,  climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [484, 340, 188], healthcare: 0.45 },
  { iso: 340, name: 'Honduras',       pop: 10000000,  climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [320, 558, 188], healthcare: 0.40 },
  { iso: 192, name: 'Cuba',           pop: 11000000,  climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [],            healthcare: 0.70 },

  // ─── SOUTH AMERICA
  { iso: 76,  name: 'Brazil',         pop: 215000000, climate: 'tropical',  wealth: 'middle', airports: 4, ports: 3, borders: [170, 218, 604, 68, 600, 858, 862], healthcare: 0.60 },
  { iso: 170, name: 'Colombia',       pop: 52000000,  climate: 'tropical',  wealth: 'middle', airports: 3, ports: 2, borders: [76, 862, 218, 591], healthcare: 0.55 },
  { iso: 862, name: 'Venezuela',      pop: 29000000,  climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [76, 170],     healthcare: 0.35 },
  { iso: 218, name: 'Ecuador',        pop: 18000000,  climate: 'tropical',  wealth: 'middle', airports: 2, ports: 2, borders: [170, 604],    healthcare: 0.55 },
  { iso: 604, name: 'Peru',           pop: 33000000,  climate: 'arid',      wealth: 'middle', airports: 2, ports: 2, borders: [218, 76, 68, 152], healthcare: 0.50 },
  { iso: 68,  name: 'Bolivia',        pop: 12000000,  climate: 'arid',      wealth: 'poor',   airports: 1, ports: 0, borders: [76, 604, 152, 600, 32], healthcare: 0.40 },
  { iso: 32,  name: 'Argentina',      pop: 46000000,  climate: 'temperate', wealth: 'middle', airports: 3, ports: 2, borders: [76, 68, 152, 600, 858], healthcare: 0.70 },
  { iso: 152, name: 'Chile',          pop: 19000000,  climate: 'arid',      wealth: 'middle', airports: 2, ports: 2, borders: [32, 68, 604], healthcare: 0.75 },

  // ─── EUROPE
  { iso: 826, name: 'UK',             pop: 68000000,  climate: 'temperate', wealth: 'rich',   airports: 5, ports: 3, borders: [372],         healthcare: 0.90 },
  { iso: 250, name: 'France',         pop: 68000000,  climate: 'temperate', wealth: 'rich',   airports: 4, ports: 3, borders: [56, 756, 380, 724, 620, 826], healthcare: 0.93 },
  { iso: 276, name: 'Germany',        pop: 84000000,  climate: 'temperate', wealth: 'rich',   airports: 5, ports: 2, borders: [250, 56, 528, 756, 40, 203, 616, 208], healthcare: 0.94 },
  { iso: 724, name: 'Spain',          pop: 47000000,  climate: 'temperate', wealth: 'rich',   airports: 4, ports: 3, borders: [620, 250],     healthcare: 0.88 },
  { iso: 380, name: 'Italy',          pop: 60000000,  climate: 'temperate', wealth: 'rich',   airports: 4, ports: 3, borders: [250, 756, 40, 705], healthcare: 0.89 },
  { iso: 620, name: 'Portugal',       pop: 10000000,  climate: 'temperate', wealth: 'rich',   airports: 3, ports: 3, borders: [724],          healthcare: 0.85 },
  { iso: 528, name: 'Netherlands',    pop: 18000000,  climate: 'temperate', wealth: 'rich',   airports: 5, ports: 3, borders: [276, 56],       healthcare: 0.93 },
  { iso: 56,  name: 'Belgium',        pop: 11000000,  climate: 'temperate', wealth: 'rich',   airports: 3, ports: 2, borders: [276, 250, 528], healthcare: 0.91 },
  { iso: 756, name: 'Switzerland',    pop: 9000000,   climate: 'cold',      wealth: 'rich',   airports: 3, ports: 0, borders: [276, 250, 380, 40], healthcare: 0.97 },
  { iso: 40,  name: 'Austria',        pop: 9000000,   climate: 'temperate', wealth: 'rich',   airports: 2, ports: 0, borders: [276, 756, 380, 705, 348, 703, 703], healthcare: 0.90 },
  { iso: 752, name: 'Sweden',         pop: 10000000,  climate: 'cold',      wealth: 'rich',   airports: 3, ports: 2, borders: [578, 246],      healthcare: 0.95 },
  { iso: 578, name: 'Norway',         pop: 5000000,   climate: 'cold',      wealth: 'rich',   airports: 3, ports: 3, borders: [752, 246],      healthcare: 0.95 },
  { iso: 246, name: 'Finland',        pop: 6000000,   climate: 'cold',      wealth: 'rich',   airports: 2, ports: 2, borders: [752, 578, 643], healthcare: 0.94 },
  { iso: 616, name: 'Poland',         pop: 38000000,  climate: 'temperate', wealth: 'middle', airports: 3, ports: 1, borders: [276, 203, 804, 112, 643], healthcare: 0.82 },
  { iso: 804, name: 'Ukraine',        pop: 44000000,  climate: 'temperate', wealth: 'poor',   airports: 2, ports: 2, borders: [643, 616, 642, 348, 498], healthcare: 0.55 },
  { iso: 642, name: 'Romania',        pop: 19000000,  climate: 'temperate', wealth: 'middle', airports: 2, ports: 1, borders: [804, 348, 100, 703, 688], healthcare: 0.72 },
  { iso: 300, name: 'Greece',         pop: 11000000,  climate: 'temperate', wealth: 'middle', airports: 3, ports: 3, borders: [792, 100, 807, 8], healthcare: 0.78 },
  { iso: 643, name: 'Russia',         pop: 145000000, climate: 'cold',      wealth: 'middle', airports: 5, ports: 3, borders: [246, 616, 804, 112, 398, 156, 496, 408, 860], healthcare: 0.65 },

  // ─── MIDDLE EAST
  { iso: 792, name: 'Turkey',         pop: 85000000,  climate: 'temperate', wealth: 'middle', airports: 4, ports: 3, borders: [300, 100, 364, 368, 760], healthcare: 0.72 },
  { iso: 682, name: 'Saudi Arabia',   pop: 36000000,  climate: 'arid',      wealth: 'rich',   airports: 4, ports: 2, borders: [400, 368, 887, 784, 512], healthcare: 0.80 },
  { iso: 364, name: 'Iran',           pop: 86000000,  climate: 'arid',      wealth: 'middle', airports: 3, ports: 2, borders: [792, 368, 760, 398, 860], healthcare: 0.65 },
  { iso: 368, name: 'Iraq',           pop: 42000000,  climate: 'arid',      wealth: 'middle', airports: 2, ports: 1, borders: [792, 364, 682, 400, 760, 422], healthcare: 0.55 },
  { iso: 376, name: 'Israel',         pop: 9000000,   climate: 'arid',      wealth: 'rich',   airports: 3, ports: 2, borders: [422, 400],     healthcare: 0.92 },

  // ─── AFRICA
  { iso: 818, name: 'Egypt',          pop: 105000000, climate: 'arid',      wealth: 'middle', airports: 3, ports: 2, borders: [729, 434, 376], healthcare: 0.60 },
  { iso: 566, name: 'Nigeria',        pop: 220000000, climate: 'tropical',  wealth: 'poor',   airports: 3, ports: 2, borders: [120, 562, 148], healthcare: 0.35 },
  { iso: 710, name: 'South Africa',   pop: 60000000,  climate: 'temperate', wealth: 'middle', airports: 4, ports: 3, borders: [516, 716, 508], healthcare: 0.65 },
  { iso: 404, name: 'Kenya',          pop: 56000000,  climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [800, 834, 706, 231], healthcare: 0.45 },
  { iso: 231, name: 'Ethiopia',       pop: 126000000, climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 0, borders: [404, 706, 729, 728], healthcare: 0.30 },
  { iso: 12,  name: 'Algeria',        pop: 46000000,  climate: 'arid',      wealth: 'middle', airports: 3, ports: 2, borders: [504, 434, 466, 562, 729, 788], healthcare: 0.60 },
  { iso: 504, name: 'Morocco',        pop: 37000000,  climate: 'arid',      wealth: 'middle', airports: 3, ports: 2, borders: [12],            healthcare: 0.62 },
  { iso: 716, name: 'Zimbabwe',       pop: 16000000,  climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [710, 516, 508, 834], healthcare: 0.32 },

  // ─── SOUTH ASIA
  { iso: 356, name: 'India',          pop: 1430000000,climate: 'tropical',  wealth: 'poor',   airports: 5, ports: 4, borders: [586, 50, 524, 156, 104, 144], healthcare: 0.50 },
  { iso: 586, name: 'Pakistan',       pop: 235000000, climate: 'arid',      wealth: 'poor',   airports: 3, ports: 2, borders: [356, 364, 4, 156], healthcare: 0.40 },
  { iso: 50,  name: 'Bangladesh',     pop: 170000000, climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [356, 104],      healthcare: 0.42 },

  // ─── EAST ASIA
  { iso: 156, name: 'China',          pop: 1412000000,climate: 'temperate', wealth: 'middle', airports: 5, ports: 5, borders: [356, 586, 643, 496, 408, 704, 418, 524], healthcare: 0.72 },
  { iso: 392, name: 'Japan',          pop: 125000000, climate: 'temperate', wealth: 'rich',   airports: 5, ports: 4, borders: [],              healthcare: 0.95 },
  { iso: 410, name: 'South Korea',    pop: 52000000,  climate: 'temperate', wealth: 'rich',   airports: 4, ports: 3, borders: [408],           healthcare: 0.90 },
  { iso: 408, name: 'North Korea',    pop: 26000000,  climate: 'cold',      wealth: 'poor',   airports: 0, ports: 1, borders: [410, 156, 643], healthcare: 0.25 },

  // ─── SOUTHEAST ASIA
  { iso: 360, name: 'Indonesia',      pop: 277000000, climate: 'tropical',  wealth: 'middle', airports: 4, ports: 4, borders: [626, 598],      healthcare: 0.55 },
  { iso: 764, name: 'Thailand',       pop: 72000000,  climate: 'tropical',  wealth: 'middle', airports: 3, ports: 3, borders: [104, 704, 418, 458], healthcare: 0.72 },
  { iso: 704, name: 'Vietnam',        pop: 98000000,  climate: 'tropical',  wealth: 'middle', airports: 3, ports: 3, borders: [156, 418, 764, 104], healthcare: 0.68 },
  { iso: 608, name: 'Philippines',    pop: 115000000, climate: 'tropical',  wealth: 'poor',   airports: 3, ports: 4, borders: [],              healthcare: 0.58 },
  { iso: 458, name: 'Malaysia',       pop: 33000000,  climate: 'tropical',  wealth: 'middle', airports: 3, ports: 3, borders: [764, 360, 96],   healthcare: 0.72 },

  // ─── OCEANIA
  { iso: 36,  name: 'Australia',      pop: 26000000,  climate: 'arid',      wealth: 'rich',   airports: 4, ports: 4, borders: [],              healthcare: 0.92 },
  { iso: 554, name: 'New Zealand',    pop: 5000000,   climate: 'temperate', wealth: 'rich',   airports: 3, ports: 2, borders: [],              healthcare: 0.93 },

  // ─── CENTRAL ASIA
  { iso: 398, name: 'Kazakhstan',     pop: 19000000,  climate: 'cold',      wealth: 'middle', airports: 2, ports: 0, borders: [643, 860, 156],  healthcare: 0.60 },

  // ─── CENTRAL AMERICA (additions)
  { iso: 188, name: 'Costa Rica',      pop: 5200000,    climate: 'tropical',  wealth: 'middle', airports: 2, ports: 2, borders: [320, 558, 591],          healthcare: 0.78 },
  { iso: 558, name: 'Nicaragua',       pop: 7000000,    climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [340, 188],               healthcare: 0.48 },
  { iso: 591, name: 'Panama',          pop: 4300000,    climate: 'tropical',  wealth: 'middle', airports: 2, ports: 3, borders: [170, 558, 188],           healthcare: 0.72 },
  { iso: 214, name: 'Dominican Rep.',  pop: 11000000,   climate: 'tropical',  wealth: 'middle', airports: 3, ports: 2, borders: [332],                    healthcare: 0.65 },
  { iso: 332, name: 'Haiti',           pop: 11500000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [214],                    healthcare: 0.20 },

  // ─── SOUTH AMERICA (additions)
  { iso: 600, name: 'Paraguay',        pop: 7400000,    climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [76, 68, 32],              healthcare: 0.48 },
  { iso: 858, name: 'Uruguay',         pop: 3600000,    climate: 'temperate', wealth: 'middle', airports: 2, ports: 2, borders: [76, 32],                  healthcare: 0.75 },

  // ─── EUROPE (additions)
  { iso: 208, name: 'Denmark',         pop: 6000000,    climate: 'temperate', wealth: 'rich',   airports: 3, ports: 3, borders: [276, 752],                healthcare: 0.93 },
  { iso: 372, name: 'Ireland',         pop: 5100000,    climate: 'temperate', wealth: 'rich',   airports: 3, ports: 3, borders: [826],                    healthcare: 0.91 },
  { iso: 203, name: 'Czech Republic',  pop: 10900000,   climate: 'temperate', wealth: 'rich',   airports: 2, ports: 0, borders: [276, 40, 703, 616],       healthcare: 0.88 },
  { iso: 703, name: 'Slovakia',        pop: 5500000,    climate: 'temperate', wealth: 'middle', airports: 1, ports: 0, borders: [203, 40, 348, 642, 616],  healthcare: 0.84 },
  { iso: 348, name: 'Hungary',         pop: 9700000,    climate: 'temperate', wealth: 'middle', airports: 2, ports: 0, borders: [40, 703, 804, 642, 688, 705, 191], healthcare: 0.82 },
  { iso: 100, name: 'Bulgaria',        pop: 6500000,    climate: 'temperate', wealth: 'middle', airports: 2, ports: 1, borders: [642, 688, 300, 792],      healthcare: 0.78 },
  { iso: 688, name: 'Serbia',          pop: 6800000,    climate: 'temperate', wealth: 'middle', airports: 1, ports: 1, borders: [100, 348, 642, 191, 705], healthcare: 0.80 },
  { iso: 705, name: 'Slovenia',        pop: 2100000,    climate: 'temperate', wealth: 'rich',   airports: 1, ports: 1, borders: [40, 380, 191, 348],       healthcare: 0.88 },
  { iso: 191, name: 'Croatia',         pop: 3900000,    climate: 'temperate', wealth: 'middle', airports: 2, ports: 2, borders: [705, 688, 348],           healthcare: 0.83 },
  { iso: 112, name: 'Belarus',         pop: 9400000,    climate: 'cold',      wealth: 'middle', airports: 1, ports: 0, borders: [616, 804, 643],           healthcare: 0.72 },

  // ─── MIDDLE EAST (additions)
  { iso: 760, name: 'Syria',           pop: 21000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 1, borders: [792, 368, 400, 422],      healthcare: 0.35 },
  { iso: 400, name: 'Jordan',          pop: 10200000,   climate: 'arid',      wealth: 'middle', airports: 2, ports: 1, borders: [682, 368, 760, 376],      healthcare: 0.74 },
  { iso: 422, name: 'Lebanon',         pop: 5500000,    climate: 'temperate', wealth: 'middle', airports: 2, ports: 2, borders: [760, 376],               healthcare: 0.78 },
  { iso: 887, name: 'Yemen',           pop: 33000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 2, borders: [682, 512],               healthcare: 0.28 },
  { iso: 784, name: 'UAE',             pop: 9900000,    climate: 'arid',      wealth: 'rich',   airports: 5, ports: 4, borders: [682, 512],               healthcare: 0.88 },
  { iso: 512, name: 'Oman',            pop: 4700000,    climate: 'arid',      wealth: 'rich',   airports: 2, ports: 2, borders: [682, 784, 887],          healthcare: 0.82 },

  // ─── AFRICA (additions)
  { iso: 788, name: 'Tunisia',         pop: 12000000,   climate: 'arid',      wealth: 'middle', airports: 2, ports: 2, borders: [12, 434],                healthcare: 0.68 },
  { iso: 434, name: 'Libya',           pop: 7200000,    climate: 'arid',      wealth: 'middle', airports: 2, ports: 1, borders: [12, 788, 818, 729, 148, 562], healthcare: 0.48 },
  { iso: 148, name: 'Chad',            pop: 17000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 0, borders: [729, 562, 566, 140, 434, 120], healthcare: 0.22 },
  { iso: 562, name: 'Niger',           pop: 24000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 0, borders: [12, 434, 148, 566, 854, 466], healthcare: 0.20 },
  { iso: 466, name: 'Mali',            pop: 22000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 0, borders: [12, 562, 854, 686],      healthcare: 0.22 },
  { iso: 854, name: 'Burkina Faso',    pop: 22000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [466, 562, 566, 288, 384], healthcare: 0.24 },
  { iso: 384, name: 'Ivory Coast',     pop: 27000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [566, 288, 854],          healthcare: 0.35 },
  { iso: 288, name: 'Ghana',           pop: 33000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [566, 854, 384],          healthcare: 0.38 },
  { iso: 686, name: 'Senegal',         pop: 17000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [466],                    healthcare: 0.45 },
  { iso: 706, name: 'Somalia',         pop: 17000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 1, borders: [231, 404],               healthcare: 0.18 },
  { iso: 729, name: 'Sudan',           pop: 45000000,   climate: 'arid',      wealth: 'poor',   airports: 2, ports: 1, borders: [818, 434, 148, 140, 728, 231], healthcare: 0.32 },
  { iso: 728, name: 'South Sudan',     pop: 11000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [729, 231, 404, 800, 180, 140], healthcare: 0.15 },
  { iso: 140, name: 'CAR',             pop: 5000000,    climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [120, 562, 729, 180, 728], healthcare: 0.15 },
  { iso: 120, name: 'Cameroon',        pop: 27000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [566, 140, 148, 178, 24],  healthcare: 0.38 },
  { iso: 178, name: 'Congo',           pop: 5800000,    climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [120, 140, 180, 24],       healthcare: 0.32 },
  { iso: 180, name: 'DR Congo',        pop: 100000000,  climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 1, borders: [178, 140, 728, 800, 646, 108, 834, 894, 24], healthcare: 0.22 },
  { iso: 800, name: 'Uganda',          pop: 46000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [180, 646, 834, 404, 728], healthcare: 0.35 },
  { iso: 646, name: 'Rwanda',          pop: 13000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [800, 180, 108, 834],      healthcare: 0.40 },
  { iso: 108, name: 'Burundi',         pop: 12000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [646, 180, 834],           healthcare: 0.30 },
  { iso: 834, name: 'Tanzania',        pop: 63000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [800, 646, 108, 180, 894, 508, 404], healthcare: 0.38 },
  { iso: 894, name: 'Zambia',          pop: 19000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [180, 834, 508, 716, 24, 516], healthcare: 0.38 },
  { iso: 508, name: 'Mozambique',      pop: 32000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 2, borders: [834, 894, 716, 710],      healthcare: 0.32 },
  { iso: 24,  name: 'Angola',          pop: 35000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [180, 178, 894, 516],      healthcare: 0.35 },
  { iso: 516, name: 'Namibia',         pop: 2500000,    climate: 'arid',      wealth: 'middle', airports: 1, ports: 1, borders: [24, 710, 894],            healthcare: 0.58 },
  { iso: 450, name: 'Madagascar',      pop: 27000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 2, borders: [],                       healthcare: 0.28 },

  // ─── SOUTH ASIA (additions)
  { iso: 104, name: 'Myanmar',         pop: 54000000,   climate: 'tropical',  wealth: 'poor',   airports: 2, ports: 2, borders: [356, 50, 156, 418, 764],  healthcare: 0.40 },
  { iso: 4,   name: 'Afghanistan',     pop: 40000000,   climate: 'arid',      wealth: 'poor',   airports: 1, ports: 0, borders: [586, 364, 860, 156],      healthcare: 0.20 },
  { iso: 524, name: 'Nepal',           pop: 30000000,   climate: 'cold',      wealth: 'poor',   airports: 1, ports: 0, borders: [356, 156],               healthcare: 0.42 },
  { iso: 144, name: 'Sri Lanka',       pop: 22000000,   climate: 'tropical',  wealth: 'middle', airports: 2, ports: 2, borders: [],                       healthcare: 0.65 },

  // ─── SOUTHEAST ASIA (additions)
  { iso: 116, name: 'Cambodia',        pop: 17000000,   climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 1, borders: [764, 704, 418],          healthcare: 0.45 },
  { iso: 418, name: 'Laos',            pop: 7000000,    climate: 'tropical',  wealth: 'poor',   airports: 1, ports: 0, borders: [156, 104, 116, 704, 764], healthcare: 0.40 },
  { iso: 702, name: 'Singapore',       pop: 5900000,    climate: 'tropical',  wealth: 'rich',   airports: 5, ports: 5, borders: [458],                    healthcare: 0.95 },

  // ─── CENTRAL ASIA (additions)
  { iso: 860, name: 'Uzbekistan',      pop: 36000000,   climate: 'arid',      wealth: 'poor',   airports: 2, ports: 0, borders: [398, 4, 762],            healthcare: 0.55 },
  { iso: 762, name: 'Tajikistan',      pop: 10000000,   climate: 'cold',      wealth: 'poor',   airports: 1, ports: 0, borders: [4, 860, 156, 398],        healthcare: 0.48 },
  { iso: 496, name: 'Mongolia',        pop: 3300000,    climate: 'cold',      wealth: 'poor',   airports: 1, ports: 0, borders: [156, 643],               healthcare: 0.52 },
];

// ─── DISEASE TYPES ───────────────────────────────
const DISEASE_TYPES = {
  bacteria: {
    name: 'Bacteria',
    icon: '🦠',
    description: 'Balanced evolution. Easiest to control.',
    infectivityMod: 1.0,
    severityMod:   1.0,
    lethalityMod:  1.0,
    cureMod:       1.0,
    dnaMod:        1.0,
    mutationRate:  0.01,
    startingTraits: [],
  },
  virus: {
    name: 'Virus',
    icon: '🔴',
    description: 'Mutates randomly. High spread potential.',
    infectivityMod: 1.2,
    severityMod:   0.9,
    lethalityMod:  1.1,
    cureMod:       1.1,
    dnaMod:        1.2,
    mutationRate:  0.04,
    startingTraits: [],
  },
  fungus: {
    name: 'Fungus',
    icon: '🍄',
    description: 'Spore bursts. Struggles to spread via travel.',
    infectivityMod: 0.85,
    severityMod:   1.0,
    lethalityMod:  0.9,
    cureMod:       0.9,
    dnaMod:        1.1,
    mutationRate:  0.005,
    startingTraits: [],
    sporeBurst: true,
  },
  parasite: {
    name: 'Parasite',
    icon: '🐛',
    description: 'Traits can be hidden. Slower but stealthy.',
    infectivityMod: 0.9,
    severityMod:   0.6,
    lethalityMod:  1.0,
    cureMod:       0.7,
    dnaMod:        0.9,
    mutationRate:  0.008,
    startingTraits: [],
    stealthy: true,
  },
  prion: {
    name: 'Prion',
    icon: '🧠',
    description: 'Extremely hard to detect. Very slow spread.',
    infectivityMod: 0.6,
    severityMod:   0.2,
    lethalityMod:  1.5,
    cureMod:       0.5,
    dnaMod:        0.7,
    mutationRate:  0.002,
    startingTraits: [],
    stealthy: true,
  },
  'nano-virus': {
    name: 'Nano-Virus',
    icon: '⚙️',
    description: 'Self-replicating nanobots. Cure research begins immediately.',
    infectivityMod: 1.3,
    severityMod:   1.2,
    lethalityMod:  1.2,
    cureMod:       1.5,
    dnaMod:        1.3,
    mutationRate:  0.02,
    startingTraits: [],
    instantCure: true,
  },
};

// ─── DIFFICULTY SETTINGS ───────────────────────────
const DIFFICULTIES = {
  casual:      { cureSpeed: 0.4, healthcareBonus: 0.8,  name: 'CASUAL',      color: '#00ff41' },
  normal:      { cureSpeed: 1.0, healthcareBonus: 1.0,  name: 'NORMAL',      color: '#ffaa00' },
  brutal:      { cureSpeed: 1.6, healthcareBonus: 1.2,  name: 'BRUTAL',      color: '#ff4400' },
  'mega-brutal': { cureSpeed: 2.5, healthcareBonus: 1.5, name: 'MEGA BRUTAL', color: '#ff0044' },
};

// ─── EVOLUTION TREE ───────────────────────────────
// Effects: infectivity, severity, lethality applied as multipliers
// Abilities can add special flags
const EVOLUTION_TREE = {
  transmissions: [
    {
      id: 'water1',
      name: 'Water 1',
      icon: '💧',
      desc: 'Pathogen survives in water. Spreads via water supply.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.08 },
      category: 'transmissions',
    },
    {
      id: 'water2',
      name: 'Water 2',
      icon: '🌊',
      desc: 'Enhanced aquatic survival. Major spread via waterways.',
      cost: 3,
      requires: ['water1'],
      effects: { infectivity: 0.12 },
      category: 'transmissions',
    },
    {
      id: 'air1',
      name: 'Airborne 1',
      icon: '💨',
      desc: 'Becomes airborne. Spreads through respiratory droplets.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.10 },
      category: 'transmissions',
    },
    {
      id: 'air2',
      name: 'Airborne 2',
      icon: '🌬️',
      desc: 'Enhanced airborne transmission. Travels long distances.',
      cost: 3,
      requires: ['air1'],
      effects: { infectivity: 0.14 },
      category: 'transmissions',
    },
    {
      id: 'extreme_bioaerosol',
      name: 'Extreme Bioaerosol',
      icon: '☁️',
      desc: 'Pathogen forms persistent aerosol clouds. Massive spread.',
      cost: 6,
      requires: ['air2'],
      effects: { infectivity: 0.20 },
      category: 'transmissions',
    },
    {
      id: 'blood1',
      name: 'Blood 1',
      icon: '🩸',
      desc: 'Spreads through blood contact and sharing needles.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.06 },
      category: 'transmissions',
    },
    {
      id: 'blood2',
      name: 'Blood 2',
      icon: '🫀',
      desc: 'Highly infectious via blood. Spreads through hospitals.',
      cost: 3,
      requires: ['blood1'],
      effects: { infectivity: 0.10, severity: 0.04 },
      category: 'transmissions',
    },
    {
      id: 'insects',
      name: 'Insect Vectors',
      icon: '🦟',
      desc: 'Spread by mosquitoes and other insects. Thrives in hot climates.',
      cost: 3,
      requires: [],
      effects: { infectivity: 0.12 },
      special: 'insect_vector',
      category: 'transmissions',
    },
    {
      id: 'rats',
      name: 'Rodent Vectors',
      icon: '🐀',
      desc: 'Spread by rats. Effective in dense urban environments.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.09 },
      category: 'transmissions',
    },
    {
      id: 'livestock',
      name: 'Livestock',
      icon: '🐄',
      desc: 'Infects farm animals. Spreads through food supply chains.',
      cost: 3,
      requires: [],
      effects: { infectivity: 0.08, severity: 0.03 },
      category: 'transmissions',
    },
    {
      id: 'saliva1',
      name: 'Saliva 1',
      icon: '🤧',
      desc: 'Spreads through saliva. Social contact accelerates spread.',
      cost: 1,
      requires: [],
      effects: { infectivity: 0.05 },
      category: 'transmissions',
    },
    {
      id: 'saliva2',
      name: 'Saliva 2',
      icon: '😷',
      desc: 'High-titer saliva shedding. Very contagious at close range.',
      cost: 2,
      requires: ['saliva1'],
      effects: { infectivity: 0.08 },
      category: 'transmissions',
    },
  ],

  symptoms: [
    {
      id: 'cough',
      name: 'Cough',
      icon: '😮‍💨',
      desc: 'Infected cough, expelling pathogens. Increases airborne spread.',
      cost: 1,
      requires: [],
      effects: { infectivity: 0.05, severity: 0.03 },
      category: 'symptoms',
    },
    {
      id: 'pneumonia',
      name: 'Pneumonia',
      icon: '🫁',
      desc: 'Lung infection. Significantly increases lethality.',
      cost: 3,
      requires: ['cough'],
      effects: { severity: 0.08, lethality: 0.06 },
      category: 'symptoms',
    },
    {
      id: 'pulmonary_fibrosis',
      name: 'Pulmonary Fibrosis',
      icon: '💀',
      desc: 'Permanent lung scarring. Extremely lethal.',
      cost: 5,
      requires: ['pneumonia'],
      effects: { lethality: 0.14, severity: 0.06 },
      category: 'symptoms',
    },
    {
      id: 'fever',
      name: 'Fever',
      icon: '🤒',
      desc: 'Elevated body temperature. Alerts healthcare systems.',
      cost: 1,
      requires: [],
      effects: { severity: 0.05, lethality: 0.01 },
      category: 'symptoms',
    },
    {
      id: 'sweating',
      name: 'Hyperhidrosis',
      icon: '🥵',
      desc: 'Excessive sweating spreads the pathogen via skin contact.',
      cost: 1,
      requires: ['fever'],
      effects: { infectivity: 0.04, severity: 0.02 },
      category: 'symptoms',
    },
    {
      id: 'hemorrhagic_shock',
      name: 'Hemorrhagic Shock',
      icon: '🩸',
      desc: 'Massive internal bleeding. Highly lethal.',
      cost: 5,
      requires: ['fever', 'sweating'],
      effects: { lethality: 0.16, severity: 0.10 },
      category: 'symptoms',
    },
    {
      id: 'nausea',
      name: 'Nausea',
      icon: '🤢',
      desc: 'Infected feel nauseous. Minor health impact.',
      cost: 1,
      requires: [],
      effects: { severity: 0.03 },
      category: 'symptoms',
    },
    {
      id: 'vomiting',
      name: 'Vomiting',
      icon: '🤮',
      desc: 'Violent vomiting contaminates water supplies.',
      cost: 2,
      requires: ['nausea'],
      effects: { infectivity: 0.06, severity: 0.05 },
      category: 'symptoms',
    },
    {
      id: 'diarrhoea',
      name: 'Diarrhoea',
      icon: '💩',
      desc: 'Contaminates water supplies. Spreads fast in poor regions.',
      cost: 2,
      requires: ['nausea'],
      effects: { infectivity: 0.07, severity: 0.04 },
      category: 'symptoms',
    },
    {
      id: 'rash',
      name: 'Skin Rash',
      icon: '🔴',
      desc: 'Visible symptoms make disease more apparent to doctors.',
      cost: 1,
      requires: [],
      effects: { severity: 0.04 },
      category: 'symptoms',
    },
    {
      id: 'necrosis',
      name: 'Necrosis',
      icon: '🧟',
      desc: 'Tissue death. Extremely high lethality.',
      cost: 5,
      requires: ['rash'],
      effects: { lethality: 0.15, severity: 0.08 },
      category: 'symptoms',
    },
    {
      id: 'seizures',
      name: 'Seizures',
      icon: '⚡',
      desc: 'Neurological damage causes seizures. High severity.',
      cost: 3,
      requires: [],
      effects: { severity: 0.08, lethality: 0.04 },
      category: 'symptoms',
    },
    {
      id: 'insanity',
      name: 'Insanity',
      icon: '🤯',
      desc: 'Psychosis causes erratic behavior, disrupting containment.',
      cost: 4,
      requires: ['seizures'],
      effects: { infectivity: 0.06, severity: 0.06, lethality: 0.05 },
      category: 'symptoms',
    },
    {
      id: 'coma',
      name: 'Coma',
      icon: '😴',
      desc: 'Infected fall into coma. Near-certain death without treatment.',
      cost: 5,
      requires: ['insanity'],
      effects: { lethality: 0.12, severity: 0.05 },
      category: 'symptoms',
    },
    {
      id: 'total_organ_failure',
      name: 'Total Organ Failure',
      icon: '💔',
      desc: 'Complete systemic shutdown. Maximum lethality.',
      cost: 7,
      requires: ['coma'],
      effects: { lethality: 0.20, severity: 0.05 },
      category: 'symptoms',
    },
  ],

  abilities: [
    {
      id: 'drug_resist1',
      name: 'Drug Resistance 1',
      icon: '💊',
      desc: 'Resists common antibiotics and antivirals. Slows cure progress.',
      cost: 3,
      requires: [],
      effects: { cureResist: 0.15 },
      category: 'abilities',
    },
    {
      id: 'drug_resist2',
      name: 'Drug Resistance 2',
      icon: '🧪',
      desc: 'Resists most pharmaceutical treatments. Major cure slowdown.',
      cost: 5,
      requires: ['drug_resist1'],
      effects: { cureResist: 0.20 },
      category: 'abilities',
    },
    {
      id: 'cold_resist1',
      name: 'Cold Resistance 1',
      icon: '❄️',
      desc: 'Survives in cold climates. Spreads in Canada, Russia, Scandinavia.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.06 },
      special: 'cold_resist',
      category: 'abilities',
    },
    {
      id: 'cold_resist2',
      name: 'Cold Resistance 2',
      icon: '🧊',
      desc: 'Thrives in cold. High-speed spread in arctic regions.',
      cost: 4,
      requires: ['cold_resist1'],
      effects: { infectivity: 0.10 },
      special: 'cold_resist2',
      category: 'abilities',
    },
    {
      id: 'heat_resist1',
      name: 'Heat Resistance 1',
      icon: '🔥',
      desc: 'Survives in hot, arid climates. Spreads in Middle East & Africa.',
      cost: 2,
      requires: [],
      effects: { infectivity: 0.06 },
      special: 'heat_resist',
      category: 'abilities',
    },
    {
      id: 'heat_resist2',
      name: 'Heat Resistance 2',
      icon: '☀️',
      desc: 'Thrives in extreme heat. Flourishes in tropical regions.',
      cost: 4,
      requires: ['heat_resist1'],
      effects: { infectivity: 0.10 },
      special: 'heat_resist2',
      category: 'abilities',
    },
    {
      id: 'resilience1',
      name: 'Bacterial Resilience 1',
      icon: '🛡️',
      desc: 'Enhanced cellular protection. Harder to identify and destroy.',
      cost: 2,
      requires: [],
      effects: { cureResist: 0.08 },
      category: 'abilities',
    },
    {
      id: 'resilience2',
      name: 'Bacterial Resilience 2',
      icon: '⚔️',
      desc: 'Near-impervious cellular wall. Highly resistant to treatment.',
      cost: 4,
      requires: ['resilience1'],
      effects: { cureResist: 0.12 },
      category: 'abilities',
    },
    {
      id: 'genetic_hardening1',
      name: 'Genetic Hardening 1',
      icon: '🔒',
      desc: 'Stabilizes genome. Reduces cure research speed significantly.',
      cost: 3,
      requires: [],
      effects: { cureResist: 0.12 },
      category: 'abilities',
    },
    {
      id: 'genetic_hardening2',
      name: 'Genetic Hardening 2',
      icon: '🔐',
      desc: 'Genome nearly impossible to sequence. Massively slows cure.',
      cost: 5,
      requires: ['genetic_hardening1'],
      effects: { cureResist: 0.18 },
      category: 'abilities',
    },
    {
      id: 'urban_survival',
      name: 'Urban Survival',
      icon: '🏙️',
      desc: 'Thrives in dense cities. Amplified spread in urban populations.',
      cost: 3,
      requires: [],
      effects: { infectivity: 0.09 },
      special: 'urban',
      category: 'abilities',
    },
    {
      id: 'rural_survival',
      name: 'Rural Adaptation',
      icon: '🌾',
      desc: 'Adapts to rural environments. Reaches isolated communities.',
      cost: 3,
      requires: [],
      effects: { infectivity: 0.07 },
      category: 'abilities',
    },
  ],
};

// ─── NEWS TEMPLATES ───────────────────────────────
const NEWS_TEMPLATES = {
  early: [
    'Health officials report unusual illness cluster in {country}',
    'Doctors puzzled by mysterious symptoms appearing in {country}',
    'WHO monitoring unusual pathogen detected in {country}',
    'Local hospitals seeing increased admissions in {country}',
    'Travel advisory issued for visitors to {country}',
  ],
  spreading: [
    '{country} declares public health emergency',
    'Pathogen confirmed in {count} countries',
    'Global infection toll passes {number}',
    'Scientists race to identify mysterious illness',
    'Airlines implement health screening procedures',
    'Schools close in multiple cities as outbreak spreads',
    'Stock markets tumble as pandemic fears grow',
    'WHO raises global alert level to highest tier',
    'International borders closed as {count} nations shut airports',
    'Cure research teams established in {count} countries',
  ],
  cure: [
    'Scientists make breakthrough in understanding pathogen structure',
    'Promising vaccine candidate enters trial phase',
    'Cure research funded with emergency government grants',
    'Global cure effort accelerated with new cooperation',
    'Lab trials show early promise against the pathogen',
    'Cure {pct}% complete — scientists optimistic',
    'Medical teams working 24/7 to complete cure',
  ],
  lethality: [
    'Death toll climbs past {number} worldwide',
    'Morgues overwhelmed in {country}',
    'Mass graves dug as {country} overwhelmed',
    'Healthcare system collapses in {country}',
    'Military deployed to enforce quarantine in {country}',
    'Looting reported as civilization breaks down in {country}',
    'Power grid failures reported in {country} as workers die',
    'Last government transmissions going dark in {country}',
  ],
  events: [
    'International aid flights suspended',
    'Scientists discover pathogen is evolving rapidly',
    'Underground bunker populations reportedly safe so far',
    'Conspiracy theories spread faster than the disease online',
    'Social media posts show desperate scenes from {country}',
    'Nobel Prize awarded posthumously to patient zero',
    'Doomsday preppers say "told you so" from undisclosed locations',
    'Satellite images show mass evacuations from major cities',
  ],
};

// ─── RANDOM EVENTS ────────────────────────────────
const RANDOM_EVENTS = [
  {
    id: 'mutation_burst',
    name: 'Random Mutation',
    message: 'The pathogen has mutated! Infectivity temporarily boosted.',
    effect: { infectivityBoost: 0.1, duration: 30 },
    probability: 0.002,
    appliesTo: ['virus'],
  },
  {
    id: 'spore_burst',
    name: 'Spore Burst',
    message: 'A massive spore release reaches a new region!',
    effect: { sporeBurst: true },
    probability: 0.003,
    appliesTo: ['fungus'],
  },
  {
    id: 'antibiotic_fail',
    name: 'Antibiotic Failure',
    message: 'Standard antibiotics found completely ineffective against pathogen.',
    effect: { cureResist: 0.1, duration: 60 },
    probability: 0.001,
  },
  {
    id: 'border_close',
    name: 'Border Closures',
    message: 'Nations begin closing borders, but disease is already global.',
    effect: { travelReduction: 0.3, duration: 90 },
    probability: 0.002,
  },
];
